name: 💡 Feature Request
description: Suggest an idea or new feature for Orilo.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Orilo even better? We'd love to hear it!

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A concise summary of your proposed feature.
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem or limitation?
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
